# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_auto_20181009_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', upload_to='posts/'),
        ),
    ]
